repos:
  - repo: local
    hooks:
      - id: pylint-db
        name: pylint-db
        entry: sh -c 'PYTHONPATH=. poetry run pylint db/models db/tests'
        language: system
        types: [python]
      - id: pylint-auth-service
        name: pylint-auth-service
        entry: cd apps/auth-service && poetry run pylint src/api src/schemas src/core
        language: system
        types: [python]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
        files: '\.py$'
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        language_version: python3
        files: '\.py$'
