services:
  db:
    image: postgres:17.5
    container_name: gameslib-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth_service:
    build:
      context: ./apps/auth_service
    container_name: auth_service
    restart: unless-stopped
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}"
      SECRET_KEY: "${SECRET_KEY:-change-this-secret}"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
volumes:
  db_data:
