"""Add description to Collection and custom_tags (JSON) to CollectionEntry

Revision ID: 8ab933b33b7f
Revises: 240008c85996
Create Date: 2025-07-10 19:13:41.213154

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8ab933b33b7f"
down_revision: Union[str, Sequence[str], None] = "240008c85996"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection_entries",
        sa.Column("custom_tags", postgresql.JSON(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("collections", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collections", "description")
    op.drop_column("collection_entries", "custom_tags")
    # ### end Alembic commands ###
